---
- block:
  # CentOS 6 'yum-utils' provides 'needs-restarting' that is too old
  - name: get latest version of needs-restarting.py
    get_url:
      url: "{{ yum_utils_url }}"
      dest: /usr/local/bin/needs-restarting
      mode: 0755

  - name: check if reboot is required
    command: /usr/local/bin/needs-restarting -r
    changed_when: false
    become: true
    register: yum_needs_reboot

  - name: reboot required
    set_fact: sys_upgrade_reboot_required=true
    when: yum_needs_reboot.rc == 1

  become: false
